bootstrapServers: localhost:9092,localhost:9093,localhost:9094
consumerGroup: andrew-hml-fhir-converter-
sessionTimeout: 10000
heartBeatInterval: 3000
minBytes: 0
autoOffsetReset: latest
maxWait: 0
maxPartitionFetchBytes: 52428800
sendBufferBytes: 32768
receiveBufferBytes: 32768
clientId: andrew-mbp-
reconnectBackoffMs: 100
retryBackoffMs: 50
metadataMaxAgeMs: 300000
connectionsMaxIdleMs: 540000
requestTimeoutMs: 305000
maxMessagesBeforeCommit: 200
hwmRefreshIntervalMs: 30000
maxPollRecords: 200
maxTimeBeforeCommit: 60000